name: Run Unittests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Create & Activate venv
        run: |
             python3 -m venv .venv
             source .venv/bin/activate
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --editable .
      - name: Run tests with pytest
        run: python3 -m unittest discover -s ./test/
